// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GoodsInfo.proto

#ifndef PROTOBUF_GoodsInfo_2eproto__INCLUDED
#define PROTOBUF_GoodsInfo_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf_GoodsInfo_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[4];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsGoodsInfo_PriceImpl();
void InitDefaultsGoodsInfo_Price();
void InitDefaultsGoodsInfo_GoodsAttrImpl();
void InitDefaultsGoodsInfo_GoodsAttr();
void InitDefaultsGoodsInfoImpl();
void InitDefaultsGoodsInfo();
void InitDefaultsGoodsInfo_ARRAYImpl();
void InitDefaultsGoodsInfo_ARRAY();
inline void InitDefaults() {
  InitDefaultsGoodsInfo_Price();
  InitDefaultsGoodsInfo_GoodsAttr();
  InitDefaultsGoodsInfo();
  InitDefaultsGoodsInfo_ARRAY();
}
}  // namespace protobuf_GoodsInfo_2eproto
namespace X {
namespace Res {
class GoodsInfo;
class GoodsInfoDefaultTypeInternal;
extern GoodsInfoDefaultTypeInternal _GoodsInfo_default_instance_;
class GoodsInfo_ARRAY;
class GoodsInfo_ARRAYDefaultTypeInternal;
extern GoodsInfo_ARRAYDefaultTypeInternal _GoodsInfo_ARRAY_default_instance_;
class GoodsInfo_GoodsAttr;
class GoodsInfo_GoodsAttrDefaultTypeInternal;
extern GoodsInfo_GoodsAttrDefaultTypeInternal _GoodsInfo_GoodsAttr_default_instance_;
class GoodsInfo_Price;
class GoodsInfo_PriceDefaultTypeInternal;
extern GoodsInfo_PriceDefaultTypeInternal _GoodsInfo_Price_default_instance_;
}  // namespace Res
}  // namespace X
namespace X {
namespace Res {

// ===================================================================

class GoodsInfo_Price : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:X.Res.GoodsInfo.Price) */ {
 public:
  GoodsInfo_Price();
  virtual ~GoodsInfo_Price();

  GoodsInfo_Price(const GoodsInfo_Price& from);

  inline GoodsInfo_Price& operator=(const GoodsInfo_Price& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GoodsInfo_Price(GoodsInfo_Price&& from) noexcept
    : GoodsInfo_Price() {
    *this = ::std::move(from);
  }

  inline GoodsInfo_Price& operator=(GoodsInfo_Price&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const GoodsInfo_Price& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GoodsInfo_Price* internal_default_instance() {
    return reinterpret_cast<const GoodsInfo_Price*>(
               &_GoodsInfo_Price_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(GoodsInfo_Price* other);
  friend void swap(GoodsInfo_Price& a, GoodsInfo_Price& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GoodsInfo_Price* New() const PROTOBUF_FINAL { return New(NULL); }

  GoodsInfo_Price* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const GoodsInfo_Price& from);
  void MergeFrom(const GoodsInfo_Price& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(GoodsInfo_Price* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint32 price_dq = 1;
  void clear_price_dq();
  static const int kPriceDqFieldNumber = 1;
  ::google::protobuf::uint32 price_dq() const;
  void set_price_dq(::google::protobuf::uint32 value);

  // uint32 price_gold = 2;
  void clear_price_gold();
  static const int kPriceGoldFieldNumber = 2;
  ::google::protobuf::uint32 price_gold() const;
  void set_price_gold(::google::protobuf::uint32 value);

  // uint32 price_value = 3;
  void clear_price_value();
  static const int kPriceValueFieldNumber = 3;
  ::google::protobuf::uint32 price_value() const;
  void set_price_value(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:X.Res.GoodsInfo.Price)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 price_dq_;
  ::google::protobuf::uint32 price_gold_;
  ::google::protobuf::uint32 price_value_;
  mutable int _cached_size_;
  friend struct ::protobuf_GoodsInfo_2eproto::TableStruct;
  friend void ::protobuf_GoodsInfo_2eproto::InitDefaultsGoodsInfo_PriceImpl();
};
// -------------------------------------------------------------------

class GoodsInfo_GoodsAttr : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:X.Res.GoodsInfo.GoodsAttr) */ {
 public:
  GoodsInfo_GoodsAttr();
  virtual ~GoodsInfo_GoodsAttr();

  GoodsInfo_GoodsAttr(const GoodsInfo_GoodsAttr& from);

  inline GoodsInfo_GoodsAttr& operator=(const GoodsInfo_GoodsAttr& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GoodsInfo_GoodsAttr(GoodsInfo_GoodsAttr&& from) noexcept
    : GoodsInfo_GoodsAttr() {
    *this = ::std::move(from);
  }

  inline GoodsInfo_GoodsAttr& operator=(GoodsInfo_GoodsAttr&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const GoodsInfo_GoodsAttr& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GoodsInfo_GoodsAttr* internal_default_instance() {
    return reinterpret_cast<const GoodsInfo_GoodsAttr*>(
               &_GoodsInfo_GoodsAttr_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(GoodsInfo_GoodsAttr* other);
  friend void swap(GoodsInfo_GoodsAttr& a, GoodsInfo_GoodsAttr& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GoodsInfo_GoodsAttr* New() const PROTOBUF_FINAL { return New(NULL); }

  GoodsInfo_GoodsAttr* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const GoodsInfo_GoodsAttr& from);
  void MergeFrom(const GoodsInfo_GoodsAttr& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(GoodsInfo_GoodsAttr* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint32 attr_type = 1;
  void clear_attr_type();
  static const int kAttrTypeFieldNumber = 1;
  ::google::protobuf::uint32 attr_type() const;
  void set_attr_type(::google::protobuf::uint32 value);

  // uint32 attr_value = 2;
  void clear_attr_value();
  static const int kAttrValueFieldNumber = 2;
  ::google::protobuf::uint32 attr_value() const;
  void set_attr_value(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:X.Res.GoodsInfo.GoodsAttr)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 attr_type_;
  ::google::protobuf::uint32 attr_value_;
  mutable int _cached_size_;
  friend struct ::protobuf_GoodsInfo_2eproto::TableStruct;
  friend void ::protobuf_GoodsInfo_2eproto::InitDefaultsGoodsInfo_GoodsAttrImpl();
};
// -------------------------------------------------------------------

class GoodsInfo : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:X.Res.GoodsInfo) */ {
 public:
  GoodsInfo();
  virtual ~GoodsInfo();

  GoodsInfo(const GoodsInfo& from);

  inline GoodsInfo& operator=(const GoodsInfo& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GoodsInfo(GoodsInfo&& from) noexcept
    : GoodsInfo() {
    *this = ::std::move(from);
  }

  inline GoodsInfo& operator=(GoodsInfo&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const GoodsInfo& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GoodsInfo* internal_default_instance() {
    return reinterpret_cast<const GoodsInfo*>(
               &_GoodsInfo_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(GoodsInfo* other);
  friend void swap(GoodsInfo& a, GoodsInfo& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GoodsInfo* New() const PROTOBUF_FINAL { return New(NULL); }

  GoodsInfo* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const GoodsInfo& from);
  void MergeFrom(const GoodsInfo& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(GoodsInfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef GoodsInfo_Price Price;
  typedef GoodsInfo_GoodsAttr GoodsAttr;

  // accessors -------------------------------------------------------

  // repeated uint32 privileged_plat_id_list = 14;
  int privileged_plat_id_list_size() const;
  void clear_privileged_plat_id_list();
  static const int kPrivilegedPlatIdListFieldNumber = 14;
  ::google::protobuf::uint32 privileged_plat_id_list(int index) const;
  void set_privileged_plat_id_list(int index, ::google::protobuf::uint32 value);
  void add_privileged_plat_id_list(::google::protobuf::uint32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      privileged_plat_id_list() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_privileged_plat_id_list();

  // repeated .X.Res.GoodsInfo.Price price_table = 27;
  int price_table_size() const;
  void clear_price_table();
  static const int kPriceTableFieldNumber = 27;
  const ::X::Res::GoodsInfo_Price& price_table(int index) const;
  ::X::Res::GoodsInfo_Price* mutable_price_table(int index);
  ::X::Res::GoodsInfo_Price* add_price_table();
  ::google::protobuf::RepeatedPtrField< ::X::Res::GoodsInfo_Price >*
      mutable_price_table();
  const ::google::protobuf::RepeatedPtrField< ::X::Res::GoodsInfo_Price >&
      price_table() const;

  // repeated .X.Res.GoodsInfo.GoodsAttr goods_attr = 28;
  int goods_attr_size() const;
  void clear_goods_attr();
  static const int kGoodsAttrFieldNumber = 28;
  const ::X::Res::GoodsInfo_GoodsAttr& goods_attr(int index) const;
  ::X::Res::GoodsInfo_GoodsAttr* mutable_goods_attr(int index);
  ::X::Res::GoodsInfo_GoodsAttr* add_goods_attr();
  ::google::protobuf::RepeatedPtrField< ::X::Res::GoodsInfo_GoodsAttr >*
      mutable_goods_attr();
  const ::google::protobuf::RepeatedPtrField< ::X::Res::GoodsInfo_GoodsAttr >&
      goods_attr() const;

  // bytes name = 2;
  void clear_name();
  static const int kNameFieldNumber = 2;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const void* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // bytes online_time = 12;
  void clear_online_time();
  static const int kOnlineTimeFieldNumber = 12;
  const ::std::string& online_time() const;
  void set_online_time(const ::std::string& value);
  #if LANG_CXX11
  void set_online_time(::std::string&& value);
  #endif
  void set_online_time(const char* value);
  void set_online_time(const void* value, size_t size);
  ::std::string* mutable_online_time();
  ::std::string* release_online_time();
  void set_allocated_online_time(::std::string* online_time);

  // bytes offline_time = 13;
  void clear_offline_time();
  static const int kOfflineTimeFieldNumber = 13;
  const ::std::string& offline_time() const;
  void set_offline_time(const ::std::string& value);
  #if LANG_CXX11
  void set_offline_time(::std::string&& value);
  #endif
  void set_offline_time(const char* value);
  void set_offline_time(const void* value, size_t size);
  ::std::string* mutable_offline_time();
  ::std::string* release_offline_time();
  void set_allocated_offline_time(::std::string* offline_time);

  // bytes valid_time = 19;
  void clear_valid_time();
  static const int kValidTimeFieldNumber = 19;
  const ::std::string& valid_time() const;
  void set_valid_time(const ::std::string& value);
  #if LANG_CXX11
  void set_valid_time(::std::string&& value);
  #endif
  void set_valid_time(const char* value);
  void set_valid_time(const void* value, size_t size);
  ::std::string* mutable_valid_time();
  ::std::string* release_valid_time();
  void set_allocated_valid_time(::std::string* valid_time);

  // bytes status = 23;
  void clear_status();
  static const int kStatusFieldNumber = 23;
  const ::std::string& status() const;
  void set_status(const ::std::string& value);
  #if LANG_CXX11
  void set_status(::std::string&& value);
  #endif
  void set_status(const char* value);
  void set_status(const void* value, size_t size);
  ::std::string* mutable_status();
  ::std::string* release_status();
  void set_allocated_status(::std::string* status);

  // bytes description = 29;
  void clear_description();
  static const int kDescriptionFieldNumber = 29;
  const ::std::string& description() const;
  void set_description(const ::std::string& value);
  #if LANG_CXX11
  void set_description(::std::string&& value);
  #endif
  void set_description(const char* value);
  void set_description(const void* value, size_t size);
  ::std::string* mutable_description();
  ::std::string* release_description();
  void set_allocated_description(::std::string* description);

  // bytes subSystemId = 31;
  void clear_subsystemid();
  static const int kSubSystemIdFieldNumber = 31;
  const ::std::string& subsystemid() const;
  void set_subsystemid(const ::std::string& value);
  #if LANG_CXX11
  void set_subsystemid(::std::string&& value);
  #endif
  void set_subsystemid(const char* value);
  void set_subsystemid(const void* value, size_t size);
  ::std::string* mutable_subsystemid();
  ::std::string* release_subsystemid();
  void set_allocated_subsystemid(::std::string* subsystemid);

  // uint32 goods_id = 1;
  void clear_goods_id();
  static const int kGoodsIdFieldNumber = 1;
  ::google::protobuf::uint32 goods_id() const;
  void set_goods_id(::google::protobuf::uint32 value);

  // uint32 sex = 3;
  void clear_sex();
  static const int kSexFieldNumber = 3;
  ::google::protobuf::uint32 sex() const;
  void set_sex(::google::protobuf::uint32 value);

  // uint32 level_limit = 4;
  void clear_level_limit();
  static const int kLevelLimitFieldNumber = 4;
  ::google::protobuf::uint32 level_limit() const;
  void set_level_limit(::google::protobuf::uint32 value);

  // int32 club_vip_level = 5;
  void clear_club_vip_level();
  static const int kClubVipLevelFieldNumber = 5;
  ::google::protobuf::int32 club_vip_level() const;
  void set_club_vip_level(::google::protobuf::int32 value);

  // int32 qb_2 = 6;
  void clear_qb_2();
  static const int kQb2FieldNumber = 6;
  ::google::protobuf::int32 qb_2() const;
  void set_qb_2(::google::protobuf::int32 value);

  // uint32 consume_type = 7;
  void clear_consume_type();
  static const int kConsumeTypeFieldNumber = 7;
  ::google::protobuf::uint32 consume_type() const;
  void set_consume_type(::google::protobuf::uint32 value);

  // uint32 time_unit = 8;
  void clear_time_unit();
  static const int kTimeUnitFieldNumber = 8;
  ::google::protobuf::uint32 time_unit() const;
  void set_time_unit(::google::protobuf::uint32 value);

  // uint32 is_online = 9;
  void clear_is_online();
  static const int kIsOnlineFieldNumber = 9;
  ::google::protobuf::uint32 is_online() const;
  void set_is_online(::google::protobuf::uint32 value);

  // uint32 can_buy = 10;
  void clear_can_buy();
  static const int kCanBuyFieldNumber = 10;
  ::google::protobuf::uint32 can_buy() const;
  void set_can_buy(::google::protobuf::uint32 value);

  // uint32 can_recharge = 11;
  void clear_can_recharge();
  static const int kCanRechargeFieldNumber = 11;
  ::google::protobuf::uint32 can_recharge() const;
  void set_can_recharge(::google::protobuf::uint32 value);

  // uint32 privileged_plat_is_online = 15;
  void clear_privileged_plat_is_online();
  static const int kPrivilegedPlatIsOnlineFieldNumber = 15;
  ::google::protobuf::uint32 privileged_plat_is_online() const;
  void set_privileged_plat_is_online(::google::protobuf::uint32 value);

  // uint32 privileged_plat_can_buy = 16;
  void clear_privileged_plat_can_buy();
  static const int kPrivilegedPlatCanBuyFieldNumber = 16;
  ::google::protobuf::uint32 privileged_plat_can_buy() const;
  void set_privileged_plat_can_buy(::google::protobuf::uint32 value);

  // uint32 privileged_plat_can_recharge = 17;
  void clear_privileged_plat_can_recharge();
  static const int kPrivilegedPlatCanRechargeFieldNumber = 17;
  ::google::protobuf::uint32 privileged_plat_can_recharge() const;
  void set_privileged_plat_can_recharge(::google::protobuf::uint32 value);

  // uint32 payment_terms = 18;
  void clear_payment_terms();
  static const int kPaymentTermsFieldNumber = 18;
  ::google::protobuf::uint32 payment_terms() const;
  void set_payment_terms(::google::protobuf::uint32 value);

  // uint32 sort_priority = 20;
  void clear_sort_priority();
  static const int kSortPriorityFieldNumber = 20;
  ::google::protobuf::uint32 sort_priority() const;
  void set_sort_priority(::google::protobuf::uint32 value);

  // int32 suit_number = 21;
  void clear_suit_number();
  static const int kSuitNumberFieldNumber = 21;
  ::google::protobuf::int32 suit_number() const;
  void set_suit_number(::google::protobuf::int32 value);

  // uint32 bag_sort_priority = 22;
  void clear_bag_sort_priority();
  static const int kBagSortPriorityFieldNumber = 22;
  ::google::protobuf::uint32 bag_sort_priority() const;
  void set_bag_sort_priority(::google::protobuf::uint32 value);

  // uint32 rank = 24;
  void clear_rank();
  static const int kRankFieldNumber = 24;
  ::google::protobuf::uint32 rank() const;
  void set_rank(::google::protobuf::uint32 value);

  // uint32 price_discount = 25;
  void clear_price_discount();
  static const int kPriceDiscountFieldNumber = 25;
  ::google::protobuf::uint32 price_discount() const;
  void set_price_discount(::google::protobuf::uint32 value);

  // uint32 vip_discount = 26;
  void clear_vip_discount();
  static const int kVipDiscountFieldNumber = 26;
  ::google::protobuf::uint32 vip_discount() const;
  void set_vip_discount(::google::protobuf::uint32 value);

  // uint32 limit_id = 30;
  void clear_limit_id();
  static const int kLimitIdFieldNumber = 30;
  ::google::protobuf::uint32 limit_id() const;
  void set_limit_id(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:X.Res.GoodsInfo)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > privileged_plat_id_list_;
  mutable int _privileged_plat_id_list_cached_byte_size_;
  ::google::protobuf::RepeatedPtrField< ::X::Res::GoodsInfo_Price > price_table_;
  ::google::protobuf::RepeatedPtrField< ::X::Res::GoodsInfo_GoodsAttr > goods_attr_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::internal::ArenaStringPtr online_time_;
  ::google::protobuf::internal::ArenaStringPtr offline_time_;
  ::google::protobuf::internal::ArenaStringPtr valid_time_;
  ::google::protobuf::internal::ArenaStringPtr status_;
  ::google::protobuf::internal::ArenaStringPtr description_;
  ::google::protobuf::internal::ArenaStringPtr subsystemid_;
  ::google::protobuf::uint32 goods_id_;
  ::google::protobuf::uint32 sex_;
  ::google::protobuf::uint32 level_limit_;
  ::google::protobuf::int32 club_vip_level_;
  ::google::protobuf::int32 qb_2_;
  ::google::protobuf::uint32 consume_type_;
  ::google::protobuf::uint32 time_unit_;
  ::google::protobuf::uint32 is_online_;
  ::google::protobuf::uint32 can_buy_;
  ::google::protobuf::uint32 can_recharge_;
  ::google::protobuf::uint32 privileged_plat_is_online_;
  ::google::protobuf::uint32 privileged_plat_can_buy_;
  ::google::protobuf::uint32 privileged_plat_can_recharge_;
  ::google::protobuf::uint32 payment_terms_;
  ::google::protobuf::uint32 sort_priority_;
  ::google::protobuf::int32 suit_number_;
  ::google::protobuf::uint32 bag_sort_priority_;
  ::google::protobuf::uint32 rank_;
  ::google::protobuf::uint32 price_discount_;
  ::google::protobuf::uint32 vip_discount_;
  ::google::protobuf::uint32 limit_id_;
  mutable int _cached_size_;
  friend struct ::protobuf_GoodsInfo_2eproto::TableStruct;
  friend void ::protobuf_GoodsInfo_2eproto::InitDefaultsGoodsInfoImpl();
};
// -------------------------------------------------------------------

class GoodsInfo_ARRAY : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:X.Res.GoodsInfo_ARRAY) */ {
 public:
  GoodsInfo_ARRAY();
  virtual ~GoodsInfo_ARRAY();

  GoodsInfo_ARRAY(const GoodsInfo_ARRAY& from);

  inline GoodsInfo_ARRAY& operator=(const GoodsInfo_ARRAY& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GoodsInfo_ARRAY(GoodsInfo_ARRAY&& from) noexcept
    : GoodsInfo_ARRAY() {
    *this = ::std::move(from);
  }

  inline GoodsInfo_ARRAY& operator=(GoodsInfo_ARRAY&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const GoodsInfo_ARRAY& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GoodsInfo_ARRAY* internal_default_instance() {
    return reinterpret_cast<const GoodsInfo_ARRAY*>(
               &_GoodsInfo_ARRAY_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    3;

  void Swap(GoodsInfo_ARRAY* other);
  friend void swap(GoodsInfo_ARRAY& a, GoodsInfo_ARRAY& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GoodsInfo_ARRAY* New() const PROTOBUF_FINAL { return New(NULL); }

  GoodsInfo_ARRAY* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const GoodsInfo_ARRAY& from);
  void MergeFrom(const GoodsInfo_ARRAY& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(GoodsInfo_ARRAY* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .X.Res.GoodsInfo items = 1;
  int items_size() const;
  void clear_items();
  static const int kItemsFieldNumber = 1;
  const ::X::Res::GoodsInfo& items(int index) const;
  ::X::Res::GoodsInfo* mutable_items(int index);
  ::X::Res::GoodsInfo* add_items();
  ::google::protobuf::RepeatedPtrField< ::X::Res::GoodsInfo >*
      mutable_items();
  const ::google::protobuf::RepeatedPtrField< ::X::Res::GoodsInfo >&
      items() const;

  // @@protoc_insertion_point(class_scope:X.Res.GoodsInfo_ARRAY)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::X::Res::GoodsInfo > items_;
  mutable int _cached_size_;
  friend struct ::protobuf_GoodsInfo_2eproto::TableStruct;
  friend void ::protobuf_GoodsInfo_2eproto::InitDefaultsGoodsInfo_ARRAYImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// GoodsInfo_Price

// uint32 price_dq = 1;
inline void GoodsInfo_Price::clear_price_dq() {
  price_dq_ = 0u;
}
inline ::google::protobuf::uint32 GoodsInfo_Price::price_dq() const {
  // @@protoc_insertion_point(field_get:X.Res.GoodsInfo.Price.price_dq)
  return price_dq_;
}
inline void GoodsInfo_Price::set_price_dq(::google::protobuf::uint32 value) {
  
  price_dq_ = value;
  // @@protoc_insertion_point(field_set:X.Res.GoodsInfo.Price.price_dq)
}

// uint32 price_gold = 2;
inline void GoodsInfo_Price::clear_price_gold() {
  price_gold_ = 0u;
}
inline ::google::protobuf::uint32 GoodsInfo_Price::price_gold() const {
  // @@protoc_insertion_point(field_get:X.Res.GoodsInfo.Price.price_gold)
  return price_gold_;
}
inline void GoodsInfo_Price::set_price_gold(::google::protobuf::uint32 value) {
  
  price_gold_ = value;
  // @@protoc_insertion_point(field_set:X.Res.GoodsInfo.Price.price_gold)
}

// uint32 price_value = 3;
inline void GoodsInfo_Price::clear_price_value() {
  price_value_ = 0u;
}
inline ::google::protobuf::uint32 GoodsInfo_Price::price_value() const {
  // @@protoc_insertion_point(field_get:X.Res.GoodsInfo.Price.price_value)
  return price_value_;
}
inline void GoodsInfo_Price::set_price_value(::google::protobuf::uint32 value) {
  
  price_value_ = value;
  // @@protoc_insertion_point(field_set:X.Res.GoodsInfo.Price.price_value)
}

// -------------------------------------------------------------------

// GoodsInfo_GoodsAttr

// uint32 attr_type = 1;
inline void GoodsInfo_GoodsAttr::clear_attr_type() {
  attr_type_ = 0u;
}
inline ::google::protobuf::uint32 GoodsInfo_GoodsAttr::attr_type() const {
  // @@protoc_insertion_point(field_get:X.Res.GoodsInfo.GoodsAttr.attr_type)
  return attr_type_;
}
inline void GoodsInfo_GoodsAttr::set_attr_type(::google::protobuf::uint32 value) {
  
  attr_type_ = value;
  // @@protoc_insertion_point(field_set:X.Res.GoodsInfo.GoodsAttr.attr_type)
}

// uint32 attr_value = 2;
inline void GoodsInfo_GoodsAttr::clear_attr_value() {
  attr_value_ = 0u;
}
inline ::google::protobuf::uint32 GoodsInfo_GoodsAttr::attr_value() const {
  // @@protoc_insertion_point(field_get:X.Res.GoodsInfo.GoodsAttr.attr_value)
  return attr_value_;
}
inline void GoodsInfo_GoodsAttr::set_attr_value(::google::protobuf::uint32 value) {
  
  attr_value_ = value;
  // @@protoc_insertion_point(field_set:X.Res.GoodsInfo.GoodsAttr.attr_value)
}

// -------------------------------------------------------------------

// GoodsInfo

// uint32 goods_id = 1;
inline void GoodsInfo::clear_goods_id() {
  goods_id_ = 0u;
}
inline ::google::protobuf::uint32 GoodsInfo::goods_id() const {
  // @@protoc_insertion_point(field_get:X.Res.GoodsInfo.goods_id)
  return goods_id_;
}
inline void GoodsInfo::set_goods_id(::google::protobuf::uint32 value) {
  
  goods_id_ = value;
  // @@protoc_insertion_point(field_set:X.Res.GoodsInfo.goods_id)
}

// bytes name = 2;
inline void GoodsInfo::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& GoodsInfo::name() const {
  // @@protoc_insertion_point(field_get:X.Res.GoodsInfo.name)
  return name_.GetNoArena();
}
inline void GoodsInfo::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:X.Res.GoodsInfo.name)
}
#if LANG_CXX11
inline void GoodsInfo::set_name(::std::string&& value) {
  
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:X.Res.GoodsInfo.name)
}
#endif
inline void GoodsInfo::set_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:X.Res.GoodsInfo.name)
}
inline void GoodsInfo::set_name(const void* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:X.Res.GoodsInfo.name)
}
inline ::std::string* GoodsInfo::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:X.Res.GoodsInfo.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GoodsInfo::release_name() {
  // @@protoc_insertion_point(field_release:X.Res.GoodsInfo.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GoodsInfo::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:X.Res.GoodsInfo.name)
}

// uint32 sex = 3;
inline void GoodsInfo::clear_sex() {
  sex_ = 0u;
}
inline ::google::protobuf::uint32 GoodsInfo::sex() const {
  // @@protoc_insertion_point(field_get:X.Res.GoodsInfo.sex)
  return sex_;
}
inline void GoodsInfo::set_sex(::google::protobuf::uint32 value) {
  
  sex_ = value;
  // @@protoc_insertion_point(field_set:X.Res.GoodsInfo.sex)
}

// uint32 level_limit = 4;
inline void GoodsInfo::clear_level_limit() {
  level_limit_ = 0u;
}
inline ::google::protobuf::uint32 GoodsInfo::level_limit() const {
  // @@protoc_insertion_point(field_get:X.Res.GoodsInfo.level_limit)
  return level_limit_;
}
inline void GoodsInfo::set_level_limit(::google::protobuf::uint32 value) {
  
  level_limit_ = value;
  // @@protoc_insertion_point(field_set:X.Res.GoodsInfo.level_limit)
}

// int32 club_vip_level = 5;
inline void GoodsInfo::clear_club_vip_level() {
  club_vip_level_ = 0;
}
inline ::google::protobuf::int32 GoodsInfo::club_vip_level() const {
  // @@protoc_insertion_point(field_get:X.Res.GoodsInfo.club_vip_level)
  return club_vip_level_;
}
inline void GoodsInfo::set_club_vip_level(::google::protobuf::int32 value) {
  
  club_vip_level_ = value;
  // @@protoc_insertion_point(field_set:X.Res.GoodsInfo.club_vip_level)
}

// int32 qb_2 = 6;
inline void GoodsInfo::clear_qb_2() {
  qb_2_ = 0;
}
inline ::google::protobuf::int32 GoodsInfo::qb_2() const {
  // @@protoc_insertion_point(field_get:X.Res.GoodsInfo.qb_2)
  return qb_2_;
}
inline void GoodsInfo::set_qb_2(::google::protobuf::int32 value) {
  
  qb_2_ = value;
  // @@protoc_insertion_point(field_set:X.Res.GoodsInfo.qb_2)
}

// uint32 consume_type = 7;
inline void GoodsInfo::clear_consume_type() {
  consume_type_ = 0u;
}
inline ::google::protobuf::uint32 GoodsInfo::consume_type() const {
  // @@protoc_insertion_point(field_get:X.Res.GoodsInfo.consume_type)
  return consume_type_;
}
inline void GoodsInfo::set_consume_type(::google::protobuf::uint32 value) {
  
  consume_type_ = value;
  // @@protoc_insertion_point(field_set:X.Res.GoodsInfo.consume_type)
}

// uint32 time_unit = 8;
inline void GoodsInfo::clear_time_unit() {
  time_unit_ = 0u;
}
inline ::google::protobuf::uint32 GoodsInfo::time_unit() const {
  // @@protoc_insertion_point(field_get:X.Res.GoodsInfo.time_unit)
  return time_unit_;
}
inline void GoodsInfo::set_time_unit(::google::protobuf::uint32 value) {
  
  time_unit_ = value;
  // @@protoc_insertion_point(field_set:X.Res.GoodsInfo.time_unit)
}

// uint32 is_online = 9;
inline void GoodsInfo::clear_is_online() {
  is_online_ = 0u;
}
inline ::google::protobuf::uint32 GoodsInfo::is_online() const {
  // @@protoc_insertion_point(field_get:X.Res.GoodsInfo.is_online)
  return is_online_;
}
inline void GoodsInfo::set_is_online(::google::protobuf::uint32 value) {
  
  is_online_ = value;
  // @@protoc_insertion_point(field_set:X.Res.GoodsInfo.is_online)
}

// uint32 can_buy = 10;
inline void GoodsInfo::clear_can_buy() {
  can_buy_ = 0u;
}
inline ::google::protobuf::uint32 GoodsInfo::can_buy() const {
  // @@protoc_insertion_point(field_get:X.Res.GoodsInfo.can_buy)
  return can_buy_;
}
inline void GoodsInfo::set_can_buy(::google::protobuf::uint32 value) {
  
  can_buy_ = value;
  // @@protoc_insertion_point(field_set:X.Res.GoodsInfo.can_buy)
}

// uint32 can_recharge = 11;
inline void GoodsInfo::clear_can_recharge() {
  can_recharge_ = 0u;
}
inline ::google::protobuf::uint32 GoodsInfo::can_recharge() const {
  // @@protoc_insertion_point(field_get:X.Res.GoodsInfo.can_recharge)
  return can_recharge_;
}
inline void GoodsInfo::set_can_recharge(::google::protobuf::uint32 value) {
  
  can_recharge_ = value;
  // @@protoc_insertion_point(field_set:X.Res.GoodsInfo.can_recharge)
}

// bytes online_time = 12;
inline void GoodsInfo::clear_online_time() {
  online_time_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& GoodsInfo::online_time() const {
  // @@protoc_insertion_point(field_get:X.Res.GoodsInfo.online_time)
  return online_time_.GetNoArena();
}
inline void GoodsInfo::set_online_time(const ::std::string& value) {
  
  online_time_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:X.Res.GoodsInfo.online_time)
}
#if LANG_CXX11
inline void GoodsInfo::set_online_time(::std::string&& value) {
  
  online_time_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:X.Res.GoodsInfo.online_time)
}
#endif
inline void GoodsInfo::set_online_time(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  online_time_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:X.Res.GoodsInfo.online_time)
}
inline void GoodsInfo::set_online_time(const void* value, size_t size) {
  
  online_time_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:X.Res.GoodsInfo.online_time)
}
inline ::std::string* GoodsInfo::mutable_online_time() {
  
  // @@protoc_insertion_point(field_mutable:X.Res.GoodsInfo.online_time)
  return online_time_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GoodsInfo::release_online_time() {
  // @@protoc_insertion_point(field_release:X.Res.GoodsInfo.online_time)
  
  return online_time_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GoodsInfo::set_allocated_online_time(::std::string* online_time) {
  if (online_time != NULL) {
    
  } else {
    
  }
  online_time_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), online_time);
  // @@protoc_insertion_point(field_set_allocated:X.Res.GoodsInfo.online_time)
}

// bytes offline_time = 13;
inline void GoodsInfo::clear_offline_time() {
  offline_time_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& GoodsInfo::offline_time() const {
  // @@protoc_insertion_point(field_get:X.Res.GoodsInfo.offline_time)
  return offline_time_.GetNoArena();
}
inline void GoodsInfo::set_offline_time(const ::std::string& value) {
  
  offline_time_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:X.Res.GoodsInfo.offline_time)
}
#if LANG_CXX11
inline void GoodsInfo::set_offline_time(::std::string&& value) {
  
  offline_time_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:X.Res.GoodsInfo.offline_time)
}
#endif
inline void GoodsInfo::set_offline_time(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  offline_time_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:X.Res.GoodsInfo.offline_time)
}
inline void GoodsInfo::set_offline_time(const void* value, size_t size) {
  
  offline_time_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:X.Res.GoodsInfo.offline_time)
}
inline ::std::string* GoodsInfo::mutable_offline_time() {
  
  // @@protoc_insertion_point(field_mutable:X.Res.GoodsInfo.offline_time)
  return offline_time_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GoodsInfo::release_offline_time() {
  // @@protoc_insertion_point(field_release:X.Res.GoodsInfo.offline_time)
  
  return offline_time_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GoodsInfo::set_allocated_offline_time(::std::string* offline_time) {
  if (offline_time != NULL) {
    
  } else {
    
  }
  offline_time_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), offline_time);
  // @@protoc_insertion_point(field_set_allocated:X.Res.GoodsInfo.offline_time)
}

// repeated uint32 privileged_plat_id_list = 14;
inline int GoodsInfo::privileged_plat_id_list_size() const {
  return privileged_plat_id_list_.size();
}
inline void GoodsInfo::clear_privileged_plat_id_list() {
  privileged_plat_id_list_.Clear();
}
inline ::google::protobuf::uint32 GoodsInfo::privileged_plat_id_list(int index) const {
  // @@protoc_insertion_point(field_get:X.Res.GoodsInfo.privileged_plat_id_list)
  return privileged_plat_id_list_.Get(index);
}
inline void GoodsInfo::set_privileged_plat_id_list(int index, ::google::protobuf::uint32 value) {
  privileged_plat_id_list_.Set(index, value);
  // @@protoc_insertion_point(field_set:X.Res.GoodsInfo.privileged_plat_id_list)
}
inline void GoodsInfo::add_privileged_plat_id_list(::google::protobuf::uint32 value) {
  privileged_plat_id_list_.Add(value);
  // @@protoc_insertion_point(field_add:X.Res.GoodsInfo.privileged_plat_id_list)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
GoodsInfo::privileged_plat_id_list() const {
  // @@protoc_insertion_point(field_list:X.Res.GoodsInfo.privileged_plat_id_list)
  return privileged_plat_id_list_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
GoodsInfo::mutable_privileged_plat_id_list() {
  // @@protoc_insertion_point(field_mutable_list:X.Res.GoodsInfo.privileged_plat_id_list)
  return &privileged_plat_id_list_;
}

// uint32 privileged_plat_is_online = 15;
inline void GoodsInfo::clear_privileged_plat_is_online() {
  privileged_plat_is_online_ = 0u;
}
inline ::google::protobuf::uint32 GoodsInfo::privileged_plat_is_online() const {
  // @@protoc_insertion_point(field_get:X.Res.GoodsInfo.privileged_plat_is_online)
  return privileged_plat_is_online_;
}
inline void GoodsInfo::set_privileged_plat_is_online(::google::protobuf::uint32 value) {
  
  privileged_plat_is_online_ = value;
  // @@protoc_insertion_point(field_set:X.Res.GoodsInfo.privileged_plat_is_online)
}

// uint32 privileged_plat_can_buy = 16;
inline void GoodsInfo::clear_privileged_plat_can_buy() {
  privileged_plat_can_buy_ = 0u;
}
inline ::google::protobuf::uint32 GoodsInfo::privileged_plat_can_buy() const {
  // @@protoc_insertion_point(field_get:X.Res.GoodsInfo.privileged_plat_can_buy)
  return privileged_plat_can_buy_;
}
inline void GoodsInfo::set_privileged_plat_can_buy(::google::protobuf::uint32 value) {
  
  privileged_plat_can_buy_ = value;
  // @@protoc_insertion_point(field_set:X.Res.GoodsInfo.privileged_plat_can_buy)
}

// uint32 privileged_plat_can_recharge = 17;
inline void GoodsInfo::clear_privileged_plat_can_recharge() {
  privileged_plat_can_recharge_ = 0u;
}
inline ::google::protobuf::uint32 GoodsInfo::privileged_plat_can_recharge() const {
  // @@protoc_insertion_point(field_get:X.Res.GoodsInfo.privileged_plat_can_recharge)
  return privileged_plat_can_recharge_;
}
inline void GoodsInfo::set_privileged_plat_can_recharge(::google::protobuf::uint32 value) {
  
  privileged_plat_can_recharge_ = value;
  // @@protoc_insertion_point(field_set:X.Res.GoodsInfo.privileged_plat_can_recharge)
}

// uint32 payment_terms = 18;
inline void GoodsInfo::clear_payment_terms() {
  payment_terms_ = 0u;
}
inline ::google::protobuf::uint32 GoodsInfo::payment_terms() const {
  // @@protoc_insertion_point(field_get:X.Res.GoodsInfo.payment_terms)
  return payment_terms_;
}
inline void GoodsInfo::set_payment_terms(::google::protobuf::uint32 value) {
  
  payment_terms_ = value;
  // @@protoc_insertion_point(field_set:X.Res.GoodsInfo.payment_terms)
}

// bytes valid_time = 19;
inline void GoodsInfo::clear_valid_time() {
  valid_time_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& GoodsInfo::valid_time() const {
  // @@protoc_insertion_point(field_get:X.Res.GoodsInfo.valid_time)
  return valid_time_.GetNoArena();
}
inline void GoodsInfo::set_valid_time(const ::std::string& value) {
  
  valid_time_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:X.Res.GoodsInfo.valid_time)
}
#if LANG_CXX11
inline void GoodsInfo::set_valid_time(::std::string&& value) {
  
  valid_time_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:X.Res.GoodsInfo.valid_time)
}
#endif
inline void GoodsInfo::set_valid_time(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  valid_time_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:X.Res.GoodsInfo.valid_time)
}
inline void GoodsInfo::set_valid_time(const void* value, size_t size) {
  
  valid_time_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:X.Res.GoodsInfo.valid_time)
}
inline ::std::string* GoodsInfo::mutable_valid_time() {
  
  // @@protoc_insertion_point(field_mutable:X.Res.GoodsInfo.valid_time)
  return valid_time_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GoodsInfo::release_valid_time() {
  // @@protoc_insertion_point(field_release:X.Res.GoodsInfo.valid_time)
  
  return valid_time_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GoodsInfo::set_allocated_valid_time(::std::string* valid_time) {
  if (valid_time != NULL) {
    
  } else {
    
  }
  valid_time_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), valid_time);
  // @@protoc_insertion_point(field_set_allocated:X.Res.GoodsInfo.valid_time)
}

// uint32 sort_priority = 20;
inline void GoodsInfo::clear_sort_priority() {
  sort_priority_ = 0u;
}
inline ::google::protobuf::uint32 GoodsInfo::sort_priority() const {
  // @@protoc_insertion_point(field_get:X.Res.GoodsInfo.sort_priority)
  return sort_priority_;
}
inline void GoodsInfo::set_sort_priority(::google::protobuf::uint32 value) {
  
  sort_priority_ = value;
  // @@protoc_insertion_point(field_set:X.Res.GoodsInfo.sort_priority)
}

// int32 suit_number = 21;
inline void GoodsInfo::clear_suit_number() {
  suit_number_ = 0;
}
inline ::google::protobuf::int32 GoodsInfo::suit_number() const {
  // @@protoc_insertion_point(field_get:X.Res.GoodsInfo.suit_number)
  return suit_number_;
}
inline void GoodsInfo::set_suit_number(::google::protobuf::int32 value) {
  
  suit_number_ = value;
  // @@protoc_insertion_point(field_set:X.Res.GoodsInfo.suit_number)
}

// uint32 bag_sort_priority = 22;
inline void GoodsInfo::clear_bag_sort_priority() {
  bag_sort_priority_ = 0u;
}
inline ::google::protobuf::uint32 GoodsInfo::bag_sort_priority() const {
  // @@protoc_insertion_point(field_get:X.Res.GoodsInfo.bag_sort_priority)
  return bag_sort_priority_;
}
inline void GoodsInfo::set_bag_sort_priority(::google::protobuf::uint32 value) {
  
  bag_sort_priority_ = value;
  // @@protoc_insertion_point(field_set:X.Res.GoodsInfo.bag_sort_priority)
}

// bytes status = 23;
inline void GoodsInfo::clear_status() {
  status_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& GoodsInfo::status() const {
  // @@protoc_insertion_point(field_get:X.Res.GoodsInfo.status)
  return status_.GetNoArena();
}
inline void GoodsInfo::set_status(const ::std::string& value) {
  
  status_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:X.Res.GoodsInfo.status)
}
#if LANG_CXX11
inline void GoodsInfo::set_status(::std::string&& value) {
  
  status_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:X.Res.GoodsInfo.status)
}
#endif
inline void GoodsInfo::set_status(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  status_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:X.Res.GoodsInfo.status)
}
inline void GoodsInfo::set_status(const void* value, size_t size) {
  
  status_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:X.Res.GoodsInfo.status)
}
inline ::std::string* GoodsInfo::mutable_status() {
  
  // @@protoc_insertion_point(field_mutable:X.Res.GoodsInfo.status)
  return status_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GoodsInfo::release_status() {
  // @@protoc_insertion_point(field_release:X.Res.GoodsInfo.status)
  
  return status_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GoodsInfo::set_allocated_status(::std::string* status) {
  if (status != NULL) {
    
  } else {
    
  }
  status_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), status);
  // @@protoc_insertion_point(field_set_allocated:X.Res.GoodsInfo.status)
}

// uint32 rank = 24;
inline void GoodsInfo::clear_rank() {
  rank_ = 0u;
}
inline ::google::protobuf::uint32 GoodsInfo::rank() const {
  // @@protoc_insertion_point(field_get:X.Res.GoodsInfo.rank)
  return rank_;
}
inline void GoodsInfo::set_rank(::google::protobuf::uint32 value) {
  
  rank_ = value;
  // @@protoc_insertion_point(field_set:X.Res.GoodsInfo.rank)
}

// uint32 price_discount = 25;
inline void GoodsInfo::clear_price_discount() {
  price_discount_ = 0u;
}
inline ::google::protobuf::uint32 GoodsInfo::price_discount() const {
  // @@protoc_insertion_point(field_get:X.Res.GoodsInfo.price_discount)
  return price_discount_;
}
inline void GoodsInfo::set_price_discount(::google::protobuf::uint32 value) {
  
  price_discount_ = value;
  // @@protoc_insertion_point(field_set:X.Res.GoodsInfo.price_discount)
}

// uint32 vip_discount = 26;
inline void GoodsInfo::clear_vip_discount() {
  vip_discount_ = 0u;
}
inline ::google::protobuf::uint32 GoodsInfo::vip_discount() const {
  // @@protoc_insertion_point(field_get:X.Res.GoodsInfo.vip_discount)
  return vip_discount_;
}
inline void GoodsInfo::set_vip_discount(::google::protobuf::uint32 value) {
  
  vip_discount_ = value;
  // @@protoc_insertion_point(field_set:X.Res.GoodsInfo.vip_discount)
}

// repeated .X.Res.GoodsInfo.Price price_table = 27;
inline int GoodsInfo::price_table_size() const {
  return price_table_.size();
}
inline void GoodsInfo::clear_price_table() {
  price_table_.Clear();
}
inline const ::X::Res::GoodsInfo_Price& GoodsInfo::price_table(int index) const {
  // @@protoc_insertion_point(field_get:X.Res.GoodsInfo.price_table)
  return price_table_.Get(index);
}
inline ::X::Res::GoodsInfo_Price* GoodsInfo::mutable_price_table(int index) {
  // @@protoc_insertion_point(field_mutable:X.Res.GoodsInfo.price_table)
  return price_table_.Mutable(index);
}
inline ::X::Res::GoodsInfo_Price* GoodsInfo::add_price_table() {
  // @@protoc_insertion_point(field_add:X.Res.GoodsInfo.price_table)
  return price_table_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::X::Res::GoodsInfo_Price >*
GoodsInfo::mutable_price_table() {
  // @@protoc_insertion_point(field_mutable_list:X.Res.GoodsInfo.price_table)
  return &price_table_;
}
inline const ::google::protobuf::RepeatedPtrField< ::X::Res::GoodsInfo_Price >&
GoodsInfo::price_table() const {
  // @@protoc_insertion_point(field_list:X.Res.GoodsInfo.price_table)
  return price_table_;
}

// repeated .X.Res.GoodsInfo.GoodsAttr goods_attr = 28;
inline int GoodsInfo::goods_attr_size() const {
  return goods_attr_.size();
}
inline void GoodsInfo::clear_goods_attr() {
  goods_attr_.Clear();
}
inline const ::X::Res::GoodsInfo_GoodsAttr& GoodsInfo::goods_attr(int index) const {
  // @@protoc_insertion_point(field_get:X.Res.GoodsInfo.goods_attr)
  return goods_attr_.Get(index);
}
inline ::X::Res::GoodsInfo_GoodsAttr* GoodsInfo::mutable_goods_attr(int index) {
  // @@protoc_insertion_point(field_mutable:X.Res.GoodsInfo.goods_attr)
  return goods_attr_.Mutable(index);
}
inline ::X::Res::GoodsInfo_GoodsAttr* GoodsInfo::add_goods_attr() {
  // @@protoc_insertion_point(field_add:X.Res.GoodsInfo.goods_attr)
  return goods_attr_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::X::Res::GoodsInfo_GoodsAttr >*
GoodsInfo::mutable_goods_attr() {
  // @@protoc_insertion_point(field_mutable_list:X.Res.GoodsInfo.goods_attr)
  return &goods_attr_;
}
inline const ::google::protobuf::RepeatedPtrField< ::X::Res::GoodsInfo_GoodsAttr >&
GoodsInfo::goods_attr() const {
  // @@protoc_insertion_point(field_list:X.Res.GoodsInfo.goods_attr)
  return goods_attr_;
}

// bytes description = 29;
inline void GoodsInfo::clear_description() {
  description_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& GoodsInfo::description() const {
  // @@protoc_insertion_point(field_get:X.Res.GoodsInfo.description)
  return description_.GetNoArena();
}
inline void GoodsInfo::set_description(const ::std::string& value) {
  
  description_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:X.Res.GoodsInfo.description)
}
#if LANG_CXX11
inline void GoodsInfo::set_description(::std::string&& value) {
  
  description_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:X.Res.GoodsInfo.description)
}
#endif
inline void GoodsInfo::set_description(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  description_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:X.Res.GoodsInfo.description)
}
inline void GoodsInfo::set_description(const void* value, size_t size) {
  
  description_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:X.Res.GoodsInfo.description)
}
inline ::std::string* GoodsInfo::mutable_description() {
  
  // @@protoc_insertion_point(field_mutable:X.Res.GoodsInfo.description)
  return description_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GoodsInfo::release_description() {
  // @@protoc_insertion_point(field_release:X.Res.GoodsInfo.description)
  
  return description_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GoodsInfo::set_allocated_description(::std::string* description) {
  if (description != NULL) {
    
  } else {
    
  }
  description_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), description);
  // @@protoc_insertion_point(field_set_allocated:X.Res.GoodsInfo.description)
}

// uint32 limit_id = 30;
inline void GoodsInfo::clear_limit_id() {
  limit_id_ = 0u;
}
inline ::google::protobuf::uint32 GoodsInfo::limit_id() const {
  // @@protoc_insertion_point(field_get:X.Res.GoodsInfo.limit_id)
  return limit_id_;
}
inline void GoodsInfo::set_limit_id(::google::protobuf::uint32 value) {
  
  limit_id_ = value;
  // @@protoc_insertion_point(field_set:X.Res.GoodsInfo.limit_id)
}

// bytes subSystemId = 31;
inline void GoodsInfo::clear_subsystemid() {
  subsystemid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& GoodsInfo::subsystemid() const {
  // @@protoc_insertion_point(field_get:X.Res.GoodsInfo.subSystemId)
  return subsystemid_.GetNoArena();
}
inline void GoodsInfo::set_subsystemid(const ::std::string& value) {
  
  subsystemid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:X.Res.GoodsInfo.subSystemId)
}
#if LANG_CXX11
inline void GoodsInfo::set_subsystemid(::std::string&& value) {
  
  subsystemid_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:X.Res.GoodsInfo.subSystemId)
}
#endif
inline void GoodsInfo::set_subsystemid(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  subsystemid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:X.Res.GoodsInfo.subSystemId)
}
inline void GoodsInfo::set_subsystemid(const void* value, size_t size) {
  
  subsystemid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:X.Res.GoodsInfo.subSystemId)
}
inline ::std::string* GoodsInfo::mutable_subsystemid() {
  
  // @@protoc_insertion_point(field_mutable:X.Res.GoodsInfo.subSystemId)
  return subsystemid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GoodsInfo::release_subsystemid() {
  // @@protoc_insertion_point(field_release:X.Res.GoodsInfo.subSystemId)
  
  return subsystemid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GoodsInfo::set_allocated_subsystemid(::std::string* subsystemid) {
  if (subsystemid != NULL) {
    
  } else {
    
  }
  subsystemid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), subsystemid);
  // @@protoc_insertion_point(field_set_allocated:X.Res.GoodsInfo.subSystemId)
}

// -------------------------------------------------------------------

// GoodsInfo_ARRAY

// repeated .X.Res.GoodsInfo items = 1;
inline int GoodsInfo_ARRAY::items_size() const {
  return items_.size();
}
inline void GoodsInfo_ARRAY::clear_items() {
  items_.Clear();
}
inline const ::X::Res::GoodsInfo& GoodsInfo_ARRAY::items(int index) const {
  // @@protoc_insertion_point(field_get:X.Res.GoodsInfo_ARRAY.items)
  return items_.Get(index);
}
inline ::X::Res::GoodsInfo* GoodsInfo_ARRAY::mutable_items(int index) {
  // @@protoc_insertion_point(field_mutable:X.Res.GoodsInfo_ARRAY.items)
  return items_.Mutable(index);
}
inline ::X::Res::GoodsInfo* GoodsInfo_ARRAY::add_items() {
  // @@protoc_insertion_point(field_add:X.Res.GoodsInfo_ARRAY.items)
  return items_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::X::Res::GoodsInfo >*
GoodsInfo_ARRAY::mutable_items() {
  // @@protoc_insertion_point(field_mutable_list:X.Res.GoodsInfo_ARRAY.items)
  return &items_;
}
inline const ::google::protobuf::RepeatedPtrField< ::X::Res::GoodsInfo >&
GoodsInfo_ARRAY::items() const {
  // @@protoc_insertion_point(field_list:X.Res.GoodsInfo_ARRAY.items)
  return items_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Res
}  // namespace X

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_GoodsInfo_2eproto__INCLUDED
