// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cs.proto

#ifndef _CS_MSG_
#define _CS_MSG_

#define CS_MSG_LOGIN_REQ			0			// µÇÂ½
#define CS_MSG_LOGIN_RSP			1
#define CS_MSG_CHAT_REQ				2			// ÁÄÌì
#define CS_MSG_CHAT_RSP				3
#define CS_MSG_CHAT_NTF				4

#endif
